In [1]:
import pandas as pd

In [143]:
%time st=pd.read_csv('/home/mb45296/bioinformatica/S04/Data/data_set.txt')

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.55 ms


In [3]:
st

Empty DataFrame
Columns: [CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC]
Index: []

In [6]:
st.head()

Empty DataFrame
Columns: [CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC]
Index: []

In [9]:
st.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 1 columns):
CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC    0 non-null object
dtypes: object(1)
memory usage: 0.0+ bytes


In [145]:
var1='CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCGGCCGCCGGCGCCGGCACACCGGCACAGCCGTACCGGCACAGTAGTACCGGCCGGCCGGCACACCGGCACACCGGGTACACACCGGGGCGCACACACAGGCGGGCGCCGGGCCCCGGGCCGTACCGGGCCGCCGGCGGCCCACAGGCGCCGGCACAGTACCGGCACACACAGTAGCCCACACACAGGCGGGCGGTAGCCGGCGCACACACACACAGTAGGCGCACAGCCGCCCACACACACCGGCCGGCCGGCACAGGCGGGCGGGCGCACACACACCGGCACAGTAGTAGGCGGCCGGCGCACAGCC'

In [11]:
var1[0]

'C'

In [17]:
var1.count('AC')

47

In [17]:
from collections import Counter

In [23]:
print(Counter(var1).most_common(3))

[('C', 155), ('G', 126), ('A', 68)]


In [25]:
from Bio.Seq import Seq

In [27]:
seq=Seq(var1)

In [28]:
seq

Seq('CACAGTAGGCGCCGGCACACACAGCCCCGGGCCCCGGGCCGCCCCGGGCCGGCG...GCC', Alphabet())

In [32]:
seq.count('ACC')

10

In [36]:
len(var1)

361

In [37]:
var1[0]

'C'

In [39]:
var1[1:5]

'ACAG'

In [2]:
import numpy as np 
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [42]:
var1[0:10]

'CACAGTAGGC'

In [55]:
def cuenta(str):
    a=[]
    for i in (1,len(str)):
        a[i]=str[i:10]
        
    return(a)

In [57]:
dataset='AACAAGCTGATAAACATTTAAAGAG'

In [59]:
dataset.count('A')

13

In [60]:
searchseq = CloseMatch("ATCATCGAATGGAATCTAATGGAAT", 2)

NameError: name 'CloseMatch' is not defined

In [61]:
class CloseMatch(Token):
    def __init__(self, seq, maxMismatches=1):
        super(CloseMatch,self).__init__()
        self.name = seq
        self.sequence = seq
        self.maxMismatches = maxMismatches
        self.errmsg = "Expected " + self.sequence
        self.mayIndexError = False
        self.mayReturnEmpty = False

    def parseImpl( self, instring, loc, doActions=True ):
        start = loc
        instrlen = len(instring)
        maxloc = start + len(self.sequence)

        if maxloc <= instrlen:
            seq = self.sequence
            seqloc = 0
            mismatches = []
            throwException = False
            done = False
            while loc < maxloc and not done:
                if instring[loc] != seq[seqloc]:
                    mismatches.append(seqloc)
                    if len(mismatches) > self.maxMismatches:
                        throwException = True
                        done = True
                loc += 1
                seqloc += 1
        else:
            throwException = True

        if throwException:
            exc = self.myException
            exc.loc = loc
            exc.pstr = instring
            raise exc

        return loc, (instring[start:loc],mismatches)

NameError: name 'Token' is not defined

In [62]:
len(dataset)

25

In [146]:
%time a=Counter(var1[i:i+10] for i in range(len(var1)-9))

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 259 µs


In [64]:
dataset

'AACAAGCTGATAAACATTTAAAGAG'

In [65]:
len(dataset)

25

collections.Counter

In [93]:
a=dict(a)

In [116]:
w=list(a)
wv=list(a.values())

In [112]:
w[0]

'CGGGCGGTAG'

In [117]:
wv[0]

1

In [120]:
ejem=w[0]

In [121]:
ejem[0]

'C'

In [122]:
ejem

'CGGGCGGTAG'

In [134]:
ejem[8]='T'

TypeError: 'str' object does not support item assignment

In [139]:
lista = ('a', 'b', 'c', 'b', 'a')
 
combinaciones=[]
 
for i in range(len(lista)):
    combinaciones.append([])
 
 
for a in range(len(lista)):
    combinaciones[0].append(lista[a])
    for b in range(a+1,len(lista)):
        combinaciones[1].append(lista[a] + lista[b])
        for c in range(b+1,len(lista)):
            combinaciones[2].append(lista[a] + lista[b] + lista[c])
            for d in range(c+1,len(lista)):
                combinaciones[3].append(lista[a] + lista[b]+ lista[c]+ lista[d])
                for e in range(d+1,len(lista)):
                    combinaciones[4].append(lista[a] + lista[b]+ lista[c]+ lista[d]+ lista[e])
 
print (combinaciones)

[['a', 'b', 'c', 'b', 'a'], ['ab', 'ac', 'ab', 'aa', 'bc', 'bb', 'ba', 'cb', 'ca', 'ba'], ['abc', 'abb', 'aba', 'acb', 'aca', 'aba', 'bcb', 'bca', 'bba', 'cba'], ['abcb', 'abca', 'abba', 'acba', 'bcba'], ['abcba']]


In [144]:
import itertools
result = {}
for p in itertools.combinations('0123456789',15):
    s = set('0123456789')
    s.difference_update(p)
    result[ ' '.join(sorted( [ ''.join(sorted(p)), ''.join(sorted(s)) ] )) ] = 1
print ('\n'.join(sorted(result)))

In [145]:
'ACTG'*10

'ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG'

In [146]:
'A'+'G'

'AG'

In [9]:
def selfCombine( list2Combine, length ):
    listCombined = str( ['list2Combine[i' + str( i ) + ']' for i in range( length )] ).replace( "'", '' ) \
                     + 'for i0 in range(len( list2Combine ) )'
    if length > 1:
        listCombined += str( [' for i' + str( i ) + ' in range( i' + str( i - 1 ) + ', len( list2Combine ) )' for i in range( 1, length )] )\
            .replace( "', '", ' ' )\
            .replace( "['", '' )\
            .replace( "']", '' )

    listCombined = '[' + listCombined + ']'
    listCombined = eval( listCombined )

    return listCombined

list2Combine = ['A', 'G', 'C','T']
listCombined = selfCombine( list2Combine, 5 )

In [10]:
listCombined 

[['A', 'A', 'A', 'A', 'A'],
 ['A', 'A', 'A', 'A', 'G'],
 ['A', 'A', 'A', 'A', 'C'],
 ['A', 'A', 'A', 'A', 'T'],
 ['A', 'A', 'A', 'G', 'G'],
 ['A', 'A', 'A', 'G', 'C'],
 ['A', 'A', 'A', 'G', 'T'],
 ['A', 'A', 'A', 'C', 'C'],
 ['A', 'A', 'A', 'C', 'T'],
 ['A', 'A', 'A', 'T', 'T'],
 ['A', 'A', 'G', 'G', 'G'],
 ['A', 'A', 'G', 'G', 'C'],
 ['A', 'A', 'G', 'G', 'T'],
 ['A', 'A', 'G', 'C', 'C'],
 ['A', 'A', 'G', 'C', 'T'],
 ['A', 'A', 'G', 'T', 'T'],
 ['A', 'A', 'C', 'C', 'C'],
 ['A', 'A', 'C', 'C', 'T'],
 ['A', 'A', 'C', 'T', 'T'],
 ['A', 'A', 'T', 'T', 'T'],
 ['A', 'G', 'G', 'G', 'G'],
 ['A', 'G', 'G', 'G', 'C'],
 ['A', 'G', 'G', 'G', 'T'],
 ['A', 'G', 'G', 'C', 'C'],
 ['A', 'G', 'G', 'C', 'T'],
 ['A', 'G', 'G', 'T', 'T'],
 ['A', 'G', 'C', 'C', 'C'],
 ['A', 'G', 'C', 'C', 'T'],
 ['A', 'G', 'C', 'T', 'T'],
 ['A', 'G', 'T', 'T', 'T'],
 ['A', 'C', 'C', 'C', 'C'],
 ['A', 'C', 'C', 'C', 'T'],
 ['A', 'C', 'C', 'T', 'T'],
 ['A', 'C', 'T', 'T', 'T'],
 ['A', 'T', 'T', 'T', 'T'],
 ['G', 'G', 'G', 'G'

In [11]:
len(listCombined)

56

In [13]:
L=listCombined

['A', 'A', 'A', 'A', 'A']

In [19]:
dataset='AACAAGCTGATAAACATTTAAAGAG' 
a=Counter(dataset[i:i+5] for i in range(len(dataset)-4))
a=dict(a) 
w=list(a)

In [22]:
len(w)

21

In [49]:
L[0]

['A', 'A', 'A', 'A', 'A']

In [48]:
w[0]

'ACAAG'

In [40]:
 import distance

In [47]:
distance.hamming(L[0],w[0])

2

SyntaxError: unexpected EOF while parsing (<ipython-input-83-3705983f33a5>, line 1)

In [63]:
import numpy as np
a=np.zeros((len(L),len(w)))

In [92]:
def distx(L,W):
    k=np.zeros((len(L),len(W))) 
    for i in range(len(L)): 
        for j in range(len(W)):
            k[i,j]=distance.hamming(L[i],W[j])
    return(k)  

In [93]:
wl=distx(L,w)

In [94]:
wl

array([[ 2.,  3.,  2., ...,  2.,  3.,  1.],
       [ 1.,  3.,  2., ...,  3.,  3.,  2.],
       [ 2.,  2.,  2., ...,  3.,  3.,  2.],
       ..., 
       [ 4.,  4.,  4., ...,  5.,  4.,  5.],
       [ 5.,  4.,  4., ...,  4.,  4.,  5.],
       [ 5.,  5.,  4., ...,  3.,  4.,  5.]])

In [96]:
distance.hamming(L[45],w[19])

4

In [99]:
wl[45,19]

4.0

In [100]:
print(L[45], w[19])

['G', 'C', 'C', 'C', 'C'] AAGCT


In [101]:
wl<=2

array([[ True, False,  True, ...,  True, False,  True],
       [ True, False,  True, ..., False, False,  True],
       [ True,  True,  True, ..., False, False,  True],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [106]:
freq=np.zeros(len(L))
for k in range(len(L)):
    freq[k]=sum(wl[k,:]<=2)
    

In [116]:
freq

array([ 11.,   9.,  10.,  11.,   6.,   4.,   6.,   5.,   5.,   6.,   3.,
         4.,   4.,   3.,   4.,   5.,   4.,   4.,   6.,   5.,   2.,   0.,
         1.,   1.,   1.,   3.,   1.,   3.,   3.,   4.,   0.,   3.,   3.,
         3.,   3.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   1.,
         1.,   0.,   0.,   1.,   3.,   2.,   0.,   0.,   2.,   2.,   3.,
         3.])

In [105]:
wl[1,:]

array([ 1.,  3.,  2.,  4.,  2.,  4.,  2.,  3.,  4.,  5.,  3.,  1.,  2.,
        4.,  4.,  1.,  3.,  2.,  3.,  3.,  2.])

In [117]:
import itertools

In [129]:
perms=list(itertools.product(['A','C','G','T'],repeat=5))

In [130]:
len(perms)

1024

In [131]:
ej5=distx(perms,w)

In [134]:
freq=np.zeros(len(perms))
for k in range(len(perms)):
    freq[k]=sum(ej5[k,:]<=2)
 

In [140]:
freq
%time

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.53 µs


In [136]:
max(freq)

11.0

In [139]:
perms[0]
%time

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 7.63 µs


In [138]:
%time

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 4.77 µs
